### ISSUE TITLE
Update for 2.0?

### ISSUE THREAD

**Issue by pfhor** [JavascriptIsMagic/aui#2]
Hey, I'm wondering if there's a planned update for Semantic UI 2.0? I really enjoy your approach to merging the two.

**Comment by JavascriptIsMagic** [comment]
Yes! I am already looking into it a little bit.
Aui will definitely be updated to support Semantic UI 2.0, hopefully before it comes out of beta, but I have a work project to finish up before I can focus on Aui.

**Comment by jlukic** [comment]
:+1: enjoying the approach as well

**Comment by JavascriptIsMagic** [comment]
I was expecting to get Aui 2.x out sooner, but a few things at work piled up and I wasn't able to focus on it entirely.

Aui has been streamlined to get out of the way of Semantic UI's javascript, and lets you what you need to with jQuery in `componentDidMount`

Some of the fringe features where removed in favor of letting semantic.js handle things such as forms `submit` events are no longer automatically `event.preventDefault()` because it was tricky to do reliably, and also slightly outside the scope of Aui.

Aui now mainly deals with the semantic syntax aspects, and gets out of the way for things like `$.fn.form` and `$.fn.api`

If you wish to pass in settings and behaviors through React's render, you must pass in an array: `<div ui checkbox={[]}>` or you can call it in `componentDidMount`

**Comment by jlukic** [comment]
Excellent. It's also worth noting that another fellow is keen on creating react components [over here](https://github.com/React-UI). The philosophy is a bit different, but thought I'd pass along. I've also been talking to a few people in the wings who would like to help out, but haven't started work on anything.

I'm going to be sending out an email later this week about creating official react integration(s). I'll add your name to the list. If there's room for overlap between projects, let me know.
